### ISSUE TITLE
Error: Converting circular structure to JSON

### ISSUE THREAD

**Issue by GurayCetin** [Skitionek/notify-microsoft-teams#122]
It's giving error below even it's sending message to teams. 

```
    --> starting at object with constructor 'ClientRequest'
    |     property 'res' -> object with constructor 'IncomingMessage'
    --- property 'req' closes the circle
```

action configuration below
```
      - name: notify-microsoft-teams
        uses: Skitionek/notify-microsoft-teams@11e40c38c3a629ae65a985b582eca4897b01e79e # v1.0.9
        if: failure()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
          raw: >-
            {
```
