### ISSUE TITLE
GH secretes can be returned in notifications

### ISSUE THREAD

**Issue by Miker91** [Skitionek/notify-microsoft-teams#38]
Hi,

Secrets should not be parsed and returned in the notifications. People may want to use this action having organization-wide secretes which should not be returned in clear text. 

Example:
```yaml steps:
      - uses: actions/checkout@master
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          overwrite: "{title: `Overwrote title in ${{ secrets.MS_TEAMS_WEBHOOK_URI }}`}"
```

Result:
![image](https://user-images.githubusercontent.com/46610940/194506093-b491e546-cace-4c7b-a440-999499602ddb.png)
