### ISSUE TITLE
Time to send notification is random and sometime timeout

### ISSUE THREAD

**Issue by chuongnguyen5397** [Skitionek/notify-microsoft-teams#71]
Hi,

Sometime, I see this action takes more time than expected, sometimes seeing timeout.

This is my current config:

```
- name: Microsoft Teams Notification Finish
  uses: skitionek/notify-microsoft-teams@master
  if: always()
  with:
    webhook_url: ${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URI }}
    overwrite: "{title: `Deploy success in ${workflow_link}`}"
    needs: ${{ toJson(needs) }}
    job: ${{ toJson(job) }}
    steps: ${{ toJson(steps) }}
```

 It usually takes 1 or 2 seconds to finish. But sometime It takes nearly 5 mins and I received this
 
>  Error: read ECONNRESET

![image](https://github.com/Skitionek/notify-microsoft-teams/assets/91006888/6d0a7d2b-fba0-40d0-882c-ffea3fe61e7d)

Another pipeline is success but time is also more than 2 mins

![image](https://github.com/Skitionek/notify-microsoft-teams/assets/91006888/e0d2a02c-f924-4f69-9096-67ac8b709f96)

Is it heavily depend on Network Speed or anything I'm missing to get through it?
